<?php



/* 
FITUR INI TIDAK SEPENUHNYA MENJAMIN
AKUN AMAN, TAPI INI USAHA YANG 
DAPAT SAYA LAKUKAN UNTUK MENGURANGI 
RESIKO BANNED PADA AKUN KALIAN
 */


/* DI BAWAH INI BERFUNGSI UNTUK MEMBERI
JEDA CLAIM SEBELUM TIMER DELAY DIMULAI
TERHITUNG SEJAK CLAIM SUKSES 
*/

define("maxClaim", 15);

/*
DAN DI BAWAH INI ADALAH WAKTU DELAY
UNTUK BERHENTI CLAIM SETELAH PENGHITUNGAN
CLAIM SUKSES SESUAI DENGAN YANG TERSETTING
DI ATAS
*/
define("delay", 900);



